-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-10 11:09:09 IST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ATTENDANCE 
    ( 
     AttendanceID    INTEGER  NOT NULL , 
     EventID         INTEGER , 
     UserID          INTEGER , 
     TicketID        INTEGER , 
     CkeckedInAt     DATE , 
     CheckInStatus   VARCHAR2 (100) , 
     EVENT_eventID   INTEGER  NOT NULL , 
     USER_member_id  INTEGER  NOT NULL , 
     TICKET_TicketID INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX ATTENDANCE__IDX ON ATTENDANCE 
    ( 
     TICKET_TicketID ASC 
    ) 
;

ALTER TABLE ATTENDANCE 
    ADD CONSTRAINT ATTENDANCE_PK PRIMARY KEY ( AttendanceID ) ;

CREATE TABLE Booking 
    ( 
     BookingID                    INTEGER  NOT NULL , 
     BookingReference             VARCHAR2 (30) , 
     UserID                       INTEGER , 
     EventID                      INTEGER , 
     BookingDateTime              TIMESTAMP WITH LOCAL TIME ZONE , 
     BookingStatus                VARCHAR2 (30) , 
     TotalAmount                  NUMBER (10,2) , 
     PaymentStatus                VARCHAR2 (20) , 
     CancellationReason           VARCHAR2 (500) , 
     CancelledAt                  DATE , 
     CreatedAt                    DATE , 
     USER_member_id               INTEGER  NOT NULL , 
     EVENT_eventID                INTEGER  NOT NULL , 
     TICKET_TicketID              INTEGER  NOT NULL , 
     BOOKING_PROMO_BookingPromoID INTEGER  NOT NULL , 
     PAYMENT_PayementID           INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Booking__IDX ON Booking 
    ( 
     TICKET_TicketID ASC 
    ) 
;
CREATE UNIQUE INDEX Booking__IDXv1 ON Booking 
    ( 
     BOOKING_PROMO_BookingPromoID ASC 
    ) 
;
CREATE UNIQUE INDEX Booking__IDXv2 ON Booking 
    ( 
     PAYMENT_PayementID ASC 
    ) 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_PK PRIMARY KEY ( BookingID ) ;

CREATE TABLE BOOKING_ITEM 
    ( 
     BookingItemID            INTEGER  NOT NULL , 
     BookingID                INTEGER , 
     TicketTypeID             INTEGER , 
     Quantity                 INTEGER , 
     UnitPrice                NUMBER (10,2) , 
     LineTotal                NUMBER (10,2) , 
     Booking_BookingID        INTEGER  NOT NULL , 
     Ticket_Type_TicketTypeID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE BOOKING_ITEM 
    ADD CONSTRAINT BOOKING_ITEM_PK PRIMARY KEY ( BookingItemID ) ;

CREATE TABLE BOOKING_PROMO 
    ( 
     BookingPromoID         INTEGER  NOT NULL , 
     BookingID              INTEGER , 
     PromoCodeID            INTEGER , 
     DiscountedAmount       NUMBER (10,2) , 
     AppliedAt              DATE , 
     PROMO_CODE_PromoCodeID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE BOOKING_PROMO 
    ADD CONSTRAINT BOOKING_PROMO_PK PRIMARY KEY ( BookingPromoID ) ;

CREATE TABLE EVENT 
    ( 
     eventID                    INTEGER  NOT NULL , 
     title                      VARCHAR2 (150) , 
     Description                VARCHAR2 (2000) , 
     StartDateTime              DATE  NOT NULL , 
     endDateTime                DATE , 
     venue                      VARCHAR2 (50)  NOT NULL , 
     IsOnline                   CHAR (1)  NOT NULL , 
     onlineLink                 VARCHAR2 (300) , 
     AccessibilityInfo          VARCHAR2 (500) , 
     capacity                   INTEGER , 
     visibility                 VARCHAR2 (100) , 
     status                     VARCHAR2 (30) , 
     organizerInfo              VARCHAR2 (150) , 
     Agenda                     VARCHAR2 (3000)  NOT NULL , 
     maplink                    VARCHAR2 (300)  NOT NULL , 
     createdByUserID            INTEGER , 
     organizerUnitID            INTEGER , 
     categoryID                 INTEGER , 
     createdAt                  DATE , 
     updatedAt                  DATE  NOT NULL , 
     ApprovalID                 INTEGER  NOT NULL , 
     ORGANIZER_UNIT_OrganizerID INTEGER  NOT NULL , 
     EVENT_CATEGORY_categoryID  INTEGER  NOT NULL , 
     USER_member_id             INTEGER  NOT NULL 
    ) 
;

ALTER TABLE EVENT 
    ADD CONSTRAINT EVENT_PK PRIMARY KEY ( eventID ) ;

CREATE TABLE EVENT_APPROVAL 
    ( 
     ApprovalID       INTEGER  NOT NULL , 
     EventID          INTEGER , 
     ApprovedByUserID INTEGER , 
     Decision         CHAR (1) , 
     DecisionNote     VARCHAR2 (500) , 
     DecisionDateTime DATE , 
     member_id        INTEGER  NOT NULL , 
     USER_member_id   INTEGER  NOT NULL , 
     EVENT_eventID    INTEGER 
    ) 
;

ALTER TABLE EVENT_APPROVAL 
    ADD CONSTRAINT EVENT_APPROVAL_PK PRIMARY KEY ( ApprovalID ) ;

CREATE TABLE EVENT_CATEGORY 
    ( 
     categoryID   INTEGER  NOT NULL , 
     categoryName VARCHAR2 (200) , 
     CreatedAt    DATE 
    ) 
;

ALTER TABLE EVENT_CATEGORY 
    ADD CONSTRAINT EVENT_CATEGORY_PK PRIMARY KEY ( categoryID ) ;

CREATE TABLE INQUIRY 
    ( 
     InquiryID      INTEGER  NOT NULL , 
     FullName       VARCHAR2 (120) , 
     Email          VARCHAR2 (200) , 
     category       VARCHAR2 (20) , 
     message        VARCHAR2 (500) , 
     status         VARCHAR2 (20) , 
     createdAt      DATE , 
     HandleByUserID INTEGER , 
     HandledAt      DATE , 
     ResponseNote   VARCHAR2 (300) , 
     USER_member_id INTEGER 
    ) 
;

ALTER TABLE INQUIRY 
    ADD CONSTRAINT INQUIRY_PK PRIMARY KEY ( InquiryID ) ;

CREATE TABLE ORGANIZER_UNIT 
    ( 
     OrganizerID  INTEGER  NOT NULL , 
     unittime     VARCHAR2 (120) , 
     UnitType     VARCHAR2 (30) , 
     ContactEmail VARCHAR2 (150) , 
     ContactPhone VARCHAR2 (13) , 
     status       CHAR (1) , 
     CreatedAt    DATE 
    ) 
;

ALTER TABLE ORGANIZER_UNIT 
    ADD CONSTRAINT ORGANIZER_UNIT_PK PRIMARY KEY ( OrganizerID ) ;

CREATE TABLE PAYMENT 
    ( 
     PayementID           INTEGER  NOT NULL , 
     BookingID            INTEGER , 
     PayementMethod       VARCHAR2 (30) , 
     TransactionReference VARCHAR2 (60) , 
     Amount               NUMBER (10,2) , 
     PaidAt               DATE , 
     createdAt            DATE , 
     Booking_BookingID    INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX PAYMENT__IDX ON PAYMENT 
    ( 
     Booking_BookingID ASC 
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( PayementID ) ;

CREATE TABLE PROMO_CODE 
    ( 
     PromoCodeID   INTEGER  NOT NULL , 
     code          VARCHAR2 (100) , 
     DiscountType  VARCHAR2 (20) , 
     DiscountValue NUMBER (10,2) , 
     startDate     DATE , 
     endDate       DATE , 
     IsActive      CHAR (1) , 
     createdAt     DATE 
    ) 
;

ALTER TABLE PROMO_CODE 
    ADD CONSTRAINT PROMO_CODE_PK PRIMARY KEY ( PromoCodeID ) ;

CREATE TABLE PUBLIC_EVENT_REQUEST 
    ( 
     requestID        INTEGER  NOT NULL , 
     requestFullName  VARCHAR2 (200) , 
     RequestEmail     VARCHAR2 (150) , 
     phoneNumber      VARCHAR2 (13) , 
     eventTitle       VARCHAR2 (100) , 
     Description      VARCHAR2 (2000) , 
     proposedDateTime TIMESTAMP WITH LOCAL TIME ZONE , 
     VenueorMode      VARCHAR2 (100) , 
     status           VARCHAR2 (20) , 
     reviewdNote      VARCHAR2 (500) , 
     ReviewedByUserID INTEGER , 
     CreatedAt        DATE , 
     USER_member_id   INTEGER 
    ) 
;

ALTER TABLE PUBLIC_EVENT_REQUEST 
    ADD CONSTRAINT PUBLIC_EVENT_REQUEST_PK PRIMARY KEY ( requestID ) ;

CREATE TABLE REVIEW 
    ( 
     ReviewID           INTEGER  NOT NULL , 
     enevtID            INTEGER , 
     userID             INTEGER , 
     Ratings            INTEGER , 
     "Comment"          VARCHAR2 (1000) , 
     isVerifiedAttendee CHAR (1) , 
     ReviewStatus       VARCHAR2 (50) , 
     createdAt          DATE , 
     EVENT_eventID      INTEGER , 
     USER_member_id     INTEGER 
    ) 
;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_PK PRIMARY KEY ( ReviewID ) ;

CREATE TABLE REVIEW_REPORT 
    ( 
     ReportID          INTEGER  NOT NULL , 
     ReviewID          INTEGER , 
     RepoertedByUserID INTEGER , 
     ReportReason      VARCHAR2 (500) , 
     ReportDetail      VARCHAR2 (500) , 
     ReportedAt        DATE , 
     REVIEW_ReviewID   INTEGER , 
     USER_member_id    INTEGER 
    ) 
;

ALTER TABLE REVIEW_REPORT 
    ADD CONSTRAINT REVIEW_REPORT_PK PRIMARY KEY ( ReportID ) ;

CREATE TABLE Role 
    ( 
     RoleId    INTEGER  NOT NULL , 
     rolename  VARCHAR2 (100) , 
     createdAt DATE 
    ) 
;

ALTER TABLE Role 
    ADD CONSTRAINT Role_PK PRIMARY KEY ( RoleId ) ;

CREATE TABLE TICKET 
    ( 
     TicketID                INTEGER  NOT NULL , 
     BookingID               INTEGER , 
     QRcodevalue             VARCHAR2 (100) , 
     IssuedAt                DATE , 
     Booking_BookingID       INTEGER  NOT NULL , 
     ATTENDANCE_AttendanceID INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX TICKET__IDX ON TICKET 
    ( 
     Booking_BookingID ASC 
    ) 
;
CREATE UNIQUE INDEX TICKET__IDXv1 ON TICKET 
    ( 
     ATTENDANCE_AttendanceID ASC 
    ) 
;

ALTER TABLE TICKET 
    ADD CONSTRAINT TICKET_PK PRIMARY KEY ( TicketID ) ;

CREATE TABLE Ticket_Type 
    ( 
     TicketTypeID  INTEGER  NOT NULL , 
     EventID       INTEGER , 
     TypeName      VARCHAR2 (50) , 
     Price         NUMBER (10,2) , 
     seatLimit     INTEGER , 
     salesStartAt  DATE , 
     salesEndAt    DATE , 
     IsActive      CHAR (1) , 
     createdAt     DATE , 
     EVENT_eventID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Ticket_Type 
    ADD CONSTRAINT Ticket_Type_PK PRIMARY KEY ( TicketTypeID ) ;

CREATE TABLE "USER" 
    ( 
     member_id        INTEGER  NOT NULL , 
     Full_Name        VARCHAR2 (100)  NOT NULL , 
     email            VARCHAR2 (200) , 
     phone            VARCHAR2 (13) , 
     passwordHash     VARCHAR2 (255)  NOT NULL , 
     userType         VARCHAR2 (30)  NOT NULL , 
     UniversityNumber VARCHAR2 (10)  NOT NULL , 
     Isverified       CHAR (1 CHAR) , 
     status           VARCHAR2 (20)  NOT NULL , 
     createdAt        DATE , 
     ApprovalID       INTEGER , 
     member_id2       INTEGER  NOT NULL 
    ) 
;

COMMENT ON COLUMN "USER".userType IS 'ExternelMember
UniversityMember
Organizer
Admin' 
;

ALTER TABLE "USER" 
    ADD CONSTRAINT USER_PK PRIMARY KEY ( member_id ) ;

CREATE TABLE USER_ROLE 
    ( 
     UserRoleID     INTEGER  NOT NULL , 
     roleID         INTEGER , 
     userID         INTEGER , 
     AssignedAt     DATE , 
     member_id      INTEGER  NOT NULL , 
     USER_member_id INTEGER  NOT NULL , 
     Role_RoleId    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE USER_ROLE 
    ADD CONSTRAINT USER_ROLE_PK PRIMARY KEY ( UserRoleID ) ;

CREATE TABLE WAITING_LIST 
    ( 
     WaitingListID  INTEGER  NOT NULL , 
     EventID        INTEGER , 
     UserID         INTEGER , 
     AddedAt        DATE , 
     Status         VARCHAR2 (20) , 
     NotifiedAt     DATE , 
     EVENT_eventID  INTEGER  NOT NULL , 
     USER_member_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE WAITING_LIST 
    ADD CONSTRAINT WAITING_LIST_PK PRIMARY KEY ( WaitingListID ) ;

ALTER TABLE ATTENDANCE 
    ADD CONSTRAINT ATTENDANCE_EVENT_FK FOREIGN KEY 
    ( 
     EVENT_eventID
    ) 
    REFERENCES EVENT 
    ( 
     eventID
    ) 
;

ALTER TABLE ATTENDANCE 
    ADD CONSTRAINT ATTENDANCE_TICKET_FK FOREIGN KEY 
    ( 
     TICKET_TicketID
    ) 
    REFERENCES TICKET 
    ( 
     TicketID
    ) 
;

ALTER TABLE ATTENDANCE 
    ADD CONSTRAINT ATTENDANCE_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_BOOKING_PROMO_FK FOREIGN KEY 
    ( 
     BOOKING_PROMO_BookingPromoID
    ) 
    REFERENCES BOOKING_PROMO 
    ( 
     BookingPromoID
    ) 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_EVENT_FK FOREIGN KEY 
    ( 
     EVENT_eventID
    ) 
    REFERENCES EVENT 
    ( 
     eventID
    ) 
;

ALTER TABLE BOOKING_ITEM 
    ADD CONSTRAINT BOOKING_ITEM_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingID
    ) 
    REFERENCES Booking 
    ( 
     BookingID
    ) 
;

ALTER TABLE BOOKING_ITEM 
    ADD CONSTRAINT BOOKING_ITEM_Ticket_Type_FK FOREIGN KEY 
    ( 
     Ticket_Type_TicketTypeID
    ) 
    REFERENCES Ticket_Type 
    ( 
     TicketTypeID
    ) 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_PAYMENT_FK FOREIGN KEY 
    ( 
     PAYMENT_PayementID
    ) 
    REFERENCES PAYMENT 
    ( 
     PayementID
    ) 
;

ALTER TABLE BOOKING_PROMO 
    ADD CONSTRAINT BOOKING_PROMO_PROMO_CODE_FK FOREIGN KEY 
    ( 
     PROMO_CODE_PromoCodeID
    ) 
    REFERENCES PROMO_CODE 
    ( 
     PromoCodeID
    ) 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_TICKET_FK FOREIGN KEY 
    ( 
     TICKET_TicketID
    ) 
    REFERENCES TICKET 
    ( 
     TicketID
    ) 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE EVENT_APPROVAL 
    ADD CONSTRAINT EVENT_APPROVAL_EVENT_FK FOREIGN KEY 
    ( 
     EVENT_eventID
    ) 
    REFERENCES EVENT 
    ( 
     eventID
    ) 
;

ALTER TABLE EVENT_APPROVAL 
    ADD CONSTRAINT EVENT_APPROVAL_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE EVENT 
    ADD CONSTRAINT EVENT_EVENT_CATEGORY_FK FOREIGN KEY 
    ( 
     EVENT_CATEGORY_categoryID
    ) 
    REFERENCES EVENT_CATEGORY 
    ( 
     categoryID
    ) 
;

ALTER TABLE EVENT 
    ADD CONSTRAINT EVENT_ORGANIZER_UNIT_FK FOREIGN KEY 
    ( 
     ORGANIZER_UNIT_OrganizerID
    ) 
    REFERENCES ORGANIZER_UNIT 
    ( 
     OrganizerID
    ) 
;

ALTER TABLE EVENT 
    ADD CONSTRAINT EVENT_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE INQUIRY 
    ADD CONSTRAINT INQUIRY_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT PAYMENT_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingID
    ) 
    REFERENCES Booking 
    ( 
     BookingID
    ) 
;

ALTER TABLE PUBLIC_EVENT_REQUEST 
    ADD CONSTRAINT PUBLIC_EVENT_REQUEST_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_EVENT_FK FOREIGN KEY 
    ( 
     EVENT_eventID
    ) 
    REFERENCES EVENT 
    ( 
     eventID
    ) 
;

ALTER TABLE REVIEW_REPORT 
    ADD CONSTRAINT REVIEW_REPORT_REVIEW_FK FOREIGN KEY 
    ( 
     REVIEW_ReviewID
    ) 
    REFERENCES REVIEW 
    ( 
     ReviewID
    ) 
;

ALTER TABLE REVIEW_REPORT 
    ADD CONSTRAINT REVIEW_REPORT_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE TICKET 
    ADD CONSTRAINT TICKET_ATTENDANCE_FK FOREIGN KEY 
    ( 
     ATTENDANCE_AttendanceID
    ) 
    REFERENCES ATTENDANCE 
    ( 
     AttendanceID
    ) 
;

ALTER TABLE TICKET 
    ADD CONSTRAINT TICKET_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingID
    ) 
    REFERENCES Booking 
    ( 
     BookingID
    ) 
;

ALTER TABLE Ticket_Type 
    ADD CONSTRAINT Ticket_Type_EVENT_FK FOREIGN KEY 
    ( 
     EVENT_eventID
    ) 
    REFERENCES EVENT 
    ( 
     eventID
    ) 
;

ALTER TABLE USER_ROLE 
    ADD CONSTRAINT USER_ROLE_Role_FK FOREIGN KEY 
    ( 
     Role_RoleId
    ) 
    REFERENCES Role 
    ( 
     RoleId
    ) 
;

ALTER TABLE USER_ROLE 
    ADD CONSTRAINT USER_ROLE_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;

ALTER TABLE WAITING_LIST 
    ADD CONSTRAINT WAITING_LIST_EVENT_FK FOREIGN KEY 
    ( 
     EVENT_eventID
    ) 
    REFERENCES EVENT 
    ( 
     eventID
    ) 
;

ALTER TABLE WAITING_LIST 
    ADD CONSTRAINT WAITING_LIST_USER_FK FOREIGN KEY 
    ( 
     USER_member_id
    ) 
    REFERENCES "USER" 
    ( 
     member_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            20
-- CREATE INDEX                             7
-- ALTER TABLE                             50
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
